browser=chrome
baseUrl=https://www.district.in/
headless=false
mobilePopupMsgHeading=Enter your mobile number
country_India=India
country_Other=Algeria
invalidMobileNumber1=94301548445
invalidMobileNumber2=67544788934
validMobileNumber1=9430154833
mobilePopupHeadingAfterContinue=Enter OTP